# This is an example configuration file.
Allow = [
  "clique_getSigners",
  "clique_getSignersAtHash",
  "clique_getSnapshot",
  "clique_getSnapshotAtHash",
  "clique_getVoters",
  "clique_getVotersAtHash",
  "eth_blockNumber",
  "eth_call",
  "eth_estimateGas",
  "eth_gasPrice",
  "eth_getBalance",
  "eth_getBlockByHash",
  "eth_getBlockByNumber",
  "eth_getFilterChanges",
  "eth_getLogs",
  "eth_getStorageAt",
  "eth_getTransaction",
  "eth_getTransactionCount",
  "eth_getTransactionReceipt",
  "eth_newBlockFilter",
  "eth_newPendingTransactionFilter",
  "eth_sendRawTransaction",
  "eth_totalSupply",
  "eth_uninstallFilter",
  "net_listening",
  "net_version",
]
